version: "2.3"

services:
  cvat:
    container_name: cvat
    image: cvat
    ports:
      - "8080:8080"
    build:
      context: .
      args:
        TF_ANNOTATION: "no"
        USER: "django"
        DJANGO_CONFIGURATION: "production"
        WITH_TESTS: "no"
    environment:
      DJANGO_MODWSGI_EXTRA_ARGS: ""
    volumes:
      - /home/django/data
      - /home/django/keys
      - /home/django/logs
      - /home/django/models
