version: "2.3"

services:
  cvat:
    container_name: cvat
    image: cvat
    tty: true
    ports:
      - "8080:8080"
    build:
      context: .
      args:
        TF_ANNOTATION: "no"
        USER: "django"
        DJANGO_CONFIGURATION: "production"
        WITH_TESTS: "no"
    environment:
      DJANGO_MODWSGI_EXTRA_ARGS: ""
      HOME: /home/django
      MOUNT_DIR: mnt  # /home/django/mnt
      REDIS_HOST: localhost
      DB_HOST: 127.0.0.1
    volumes:
      - /home/django/mnt
